### ISSUE TITLE
64-bit version of the Python DLL

### ISSUE THREAD

**Issue by manugarg** [pacparser/pacparser#19]
_From [jeanmarc...@gmail.com](https://code.google.com/u/114542423400589229565/) on March 08, 2012 01:50:16_

What steps will reproduce the problem? import pacparser What is the expected output? What do you see instead? expected
nothing, import succeeded
instead
Traceback \(most recent call last\):
&nbsp;&nbsp;File "&lt;stdin&gt;", line 1, in &lt;module&gt;
&nbsp;&nbsp;File "pacparser\\_\_init\_\_.py", line 31, in &lt;module&gt;
&nbsp;&nbsp;&nbsp;&nbsp;from pacparser import \_pacparser
ImportError: DLL load failed: &#37;1 is not a valid Win32 application. What version of the product are you using? On what operating system? pacparser 1.3.0 python module
Python 2.7.2 \(default, Jun 12 2011, 14:24:46\) \[MSC v.1500 64 bit \(AMD64\)\] on win32 Please provide any additional information below.

_Original issue: http://code.google.com/p/pacparser/issues/detail?id=19_

**Comment by manugarg** [comment]
This issue is not clear to me. May be some of the text got lost during transfer from google code to github. Please reopen if it's still an issue.

**Comment by bnadler** [comment]
Hi THere
I am using 32 bit version of python 2.7 on windows 7 64bit and am running into the DLL load failed error. The files and dll exist in the site- package folder. I also got this error http://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls
