### ISSUE TITLE
Hope for full support for Microsoft PAC Extension

### ISSUE THREAD

**Issue by manugarg** [pacparser/pacparser#26]
_From [hhylx1...@gmail.com](https://code.google.com/u/104628483989595225643/) on April 23, 2013 08:14:47_

Thanks for your work. I've used it to test my script for a long time. But recently, I switch to Chrome which support ipv6 extension for pac. 
I see it support a function of enable\_microsoft\_extensions\(\). It surely support dnsResolveEx\(\) function. But it lacks support for sortIpAddressList\(\).

I'm using python\_pacparser1.3.0 in ubuntu with python2.7.

Here is their definitions: http://msdn.microsoft.com/en-us/library/windows/desktop/gg308477&#37;28v=vs.85&#37;29.aspx Here is Chrome's support code: https://code.google.com/p/chromium/codesearch#chromium/src/net/proxy/proxy_resolver_v8.cc&q=sortIpA&sq=package:chromium&l=37 My test script and pac script are listed below:

_Original issue: http://code.google.com/p/pacparser/issues/detail?id=26_

**Comment by peterskurt** [comment]
I enabled enable_microsoft_extensions() but it seems as if the full set of Microsoft extensions is not supported.  I get an error with use of isInNetEx().

**Comment by manugarg** [comment]
pacparser doesn't have full support for IPv6 extensions. I am working on adding support for isResolvableEx. Support for other extensions will follow.

**Comment by manugarg** [comment]
Commit 5559ad9b988963b2283ca00092c1f37720dbac3a adds support for isInNetEx. Support for isResolvableEx was already added.

**Comment by manugarg** [comment]
I have released the new version which has support for additional *Ex routines.

Also, enable_microsoft_extensions is no longer required.
