### ISSUE TITLE
libtool: unrecognized option `-static'

### ISSUE THREAD

**Issue by manugarg** [pacparser/pacparser#30]
_From [ckujau](https://code.google.com/u/ckujau/) on December 21, 2013 01:01:26_

What steps will reproduce the problem? $ make \-C src
\[...\]
All tests were successful.
libtool \-static \-o libpacparser.a pacparser.o libjs.a
libtool: unrecognized option \`\-static'
libtool: Try \`libtool \-\-help' for more information.
make: \*\*\* \[libpacparser.a\] Error 1 What is the expected output? What do you see instead? It should compile :\-\) What version of the product are you using? On what operating system? $ libtool \-\-version | head \-1
libtool \(GNU libtool\) 2.4.2

This is on Fedora 20 \(Linux\). Please provide any additional information below. I've seen reports on the net that on MacOS the Apple version of "libtool" should be used instead. However, in this case I don't have access to this version. The manpage states \(and an old report\[0\] of this\) states, that \-\-mode must be provided, but this won't work either:

&nbsp;$&nbsp;libtool&nbsp;\-\-mode=compile&nbsp;\-static&nbsp;\-o&nbsp;libpacparser.a&nbsp;pacparser.o&nbsp;libjs.a
&nbsp;libtool:&nbsp;link:&nbsp;unrecognized&nbsp;option&nbsp;\`\-static'

\[0\] https://lists.gnu.org/archive/html/bug-libtool/2001-09/msg00015.html

_Original issue: http://code.google.com/p/pacparser/issues/detail?id=30_

**Comment by pcdummy** [comment]
Replacing the relevant part in the Makefile works for me:

**Line 93:**
<pre>
libpacparser.a: pacparser.o libjs.a
        libtool --mode=link cc -static -o libpacparser.a pacparser.o libjs.a
</pre>

**Comment by bluesangel** [comment]
Also stumbled on this issue.  Can the git src/Makefile be updated accordingly  ?

**Comment by manugarg** [comment]
Commit 6aec218 should fix this. I'll cut a new release soon.

**Comment by manugarg** [comment]
Dropped the requirement for libtool completely. Commit 6f54eae. This change has been released as part of 1.3.4.
