### ISSUE TITLE
URLs are not correctly escaped when emitting JavaScript

### ISSUE THREAD

**Issue by Flameeyes** [pacparser/pacparser#38]
https://github.com/pacparser/pacparser/blob/c54b2db142591650846e9b8359f4e6b6d5081356/src/pacparser.c#L446

The single quote character is used to contain the URL but it is not escaped in the URL; if an URL with `'` inside it is passed to the function, it'll cause a parsing error. Even more worrisome, it could lead to at code execution in the given spidermonkey as the URL can encode JavaScript by itself.

**Comment by manugarg** [comment]
Last commit (a55c90b) fixed this issue.
