### ISSUE TITLE
Fix install Instructions

### ISSUE THREAD

**Issue by donestefan** [pacparser/pacparser#39]
The [INSTALL](https://github.com/pacparser/pacparser/blob/master/INSTALL) file mentions

```
On Win-32 Systems:
#################

Binary Distribution:
===================

Compiled packages for win32 systems can be downloaded from:
http://code.google.com/p/pacparser/downloads/list
```
The Link is broken. Please update the current location for Win Binary Distribution

**Comment by manugarg** [comment]
Fixed. Thanks a lot for noticing.
