### ISSUE TITLE
Provide python3 installation for windows

### ISSUE THREAD

**Issue by mattseymour** [pacparser/pacparser#41]
It would be good if you could provide a python3 build for windows. Is this something which is possible?

Turns out python3 is supported but there is a syntax error in the code. I will attach a merge request.

**Comment by manugarg** [comment]
New release 1.3.3 includes a build for python 3 on Windows. 
https://github.com/pacparser/pacparser/releases/download/1.3.3/pacparser-python34-1.3.3-win32.zip
