### ISSUE TITLE
Cannot install Pacparser on Mac

### ISSUE THREAD

**Issue by swata12345** [pacparser/pacparser#71]
Tried to install the pac parser-1.3.5-12530.dmg on my mac.  

Error this package is incompatible with this version of OS X and may fail to install.
Installation fails right after that..

MAC OSX 10.11.3

**Comment by Boran** [comment]
I got this too, so then tried to compile, but no luck there either

> $ sudo make -C src install
Password:
echo "Running tests for pactester."
Running tests for pactester.
NO_INTERNET= ../tests/runtests.sh
All tests were successful.
install -d /usr/lib /usr/include /usr/bin
install: chmod 755 /usr/lib: Operation not permitted
install: chmod 755 /usr/include: Operation not permitted
install: chmod 755 /usr/bin: Operation not permitted
install -m 644 libpacparser.1.dylib /usr/lib/libpacparser.1.dylib
install: /usr/lib/libpacparser.1.dylib: Operation not permitted
make: *** [install] Error 71

uname -a
Darwin UM00121 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

**Comment by manugarg** [comment]
Fixed by logich in #84.

**Comment by manugarg** [comment]
Keeping it open until new release.

**Comment by grahampugh** [comment]
I also couldn't install, as sudo was required but root cannot perform `export NO_INTERNET=1`. Why is an internet test required to compile?

**Comment by manugarg** [comment]
Fixed in 1.3.7.

grahampugh@, I think the issue you're encountering with the tests is same as #79.
