### ISSUE TITLE
Wrong answer for URL with port 

### ISSUE THREAD

**Issue by kujiy** [pacparser/pacparser#81]
Why pacparser changes the answer between url with or without port?
Is this a problem of pacparser?

```javascript
// my.pac
if ( shExpMatch( host, "*.my-company.com" ) ) {          // "host" doesn't contain port
       return "DIRECT";  
}
```

```py
 pacparser.just_find_proxy("my.pac", "http://www.my-company.com")     # DIRECT
 pacparser.just_find_proxy("my.pac", "http://www.my-company.com:9000") # PROXY my-proxy.com:8080
```

**Comment by manugarg** [comment]
As per specification, host should not contain the port number, while pacparser python module includes it. It's an easy fix, but will require new release and hence testing and all.

As a workaround, I'd recommend that you pass the host to the just_find_proxy function:
  pacparser.just_find_proxy("my.pac", "http://www.my-company.com:9000", "www.my-company.com")

Thanks for reporting this issue.

**Comment by manugarg** [comment]
Fixed in the code by #82.

**Comment by manugarg** [comment]
Keeping it open until new release.

**Comment by manugarg** [comment]
Cut a new release. Apart from the source tarball, uploaded only Mac package for now.
